/*
 * This source file was generated by the Gradle 'init' task
 */
package my.project

class App {
    val greeting: String
        get() {
          // connect to an external service to get the greeting
          // suppose that this service is VERY expensive to call
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
}


// Dependency (This needs to be MOCKED)
interface UserRepository {
    fun exists(username: String): Boolean
}

// for the PROD environment
// we can create a class that implements UserRepository
class RealUserRepository : UserRepository {
    override fun exists(username: String): Boolean {
        // Simulate an expensive operation, e.g., a database or network call
        Thread.sleep(1000) // Simulating delay
        // In a real implementation, check if the user exists in the data source
        return false // Placeholder implementation
    }
}

// System Under Test (SUT)
class UserValidator(private val repository: UserRepository) {
    fun isValid(username: String): Boolean {
        // 1. Basic format validation
        if (username.length < 5) return false
        if (username.contains(' ')) return false
        
        // 2. External check (expensive operation we want to AVOID in tests)
        return !repository.exists(username)
    }
}
